# Generated by Django 5.2.3 on 2025-08-13 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_question_answered', models.BooleanField(default=True)),
                ('email_answer_accepted', models.BooleanField(default=True)),
                ('email_question_upvoted', models.BooleanField(default=False)),
                ('email_answer_upvoted', models.BooleanField(default=True)),
                ('email_user_followed', models.BooleanField(default=True)),
                ('email_tag_questions', models.BooleanField(default=False)),
                ('email_job_applications', models.BooleanField(default=True)),
                ('app_question_answered', models.BooleanField(default=True)),
                ('app_answer_accepted', models.BooleanField(default=True)),
                ('app_question_upvoted', models.BooleanField(default=True)),
                ('app_answer_upvoted', models.BooleanField(default=True)),
                ('app_user_followed', models.BooleanField(default=True)),
                ('app_tag_questions', models.BooleanField(default=True)),
                ('app_job_applications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('question_answered', 'Your question was answered'), ('answer_accepted', 'Your answer was accepted'), ('question_upvoted', 'Your question was upvoted'), ('answer_upvoted', 'Your answer was upvoted'), ('question_commented', 'Someone commented on your question'), ('answer_commented', 'Someone commented on your answer'), ('user_followed', 'Someone followed you'), ('tag_question', 'New question in followed tag'), ('badge_earned', 'You earned a new badge'), ('job_applied', 'Someone applied to your job posting'), ('job_status_changed', 'Your job application status changed')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('content_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
